name: Docker

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  docker:
    with:
      ci-lint-skip: true
      ci-test-skip: true
      dockerfile: Dockerfile
    uses: node-real/github-workflows/.github/workflows/ci-pr.yml@v1
    secrets: inherit
